name: Companion Module Checks

on:
  push:
  pull_request:

jobs:
  check:
    name: Check module / Package module
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x

      - name: Prepare environment
        run: |
          corepack enable
          corepack prepare yarn@4.17.0 --activate

      - name: Install dependencies
        run: yarn install --immutable
        env:
          CI: true

      - name: Lint
        run: yarn lint
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

      - name: Package module
        run: yarn package
        env:
          CI: true
